- hosts: local
  connection: local
  become: yes
  become_user: root

  tasks:
    # tried to use docker_container_module could not debug error.
    # - name: Run jenkins container.
    #  command: 'docker run -d --name jenkins-builder -v var/app/jenkins_home:/var/jenkins_home -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts'
    
    - name: Setup python-jenkins
      pip:
        name: python-jenkins
        state: forcereinstall

    # tried using the jenkins_job module could not trigger the build even when getting an OK message.
    - name: Queue build of a project in Jenkins
      uri:
        url: http://localhost:8080/job/fetcher-hello-world/build?token=e557dfd98441a8bbd2f4b198cd21e531"
        method: POST
        user: fetchr-admin
        password: someadminpassword
        force_basic_auth: yes
        status_code: 201
    
    - name: Poll to wait until jenkins releases compiled .war file
      command: docker cp jenkins-builder:/var/jenkins_home/ /host/path/target 
      async: 360
      poll: 15